my_app/product/models.py
PRODUCTS = {
        'iphone': {
            'name': 'iPhone 5S',
            'category': 'Phones',
            'price': 699,
            },
        'galaxy': {
            'name': 'Samsung Galaxy 5',
            'category': 'Phones',
            'price': 649,
            },
        'ipad-air': {
            'name': 'iPad Air',
            'category': 'Tablets',
            'price': 649,

            },
        'ipad-mini': {
            'name': 'iPad Mini',
            'category': 'Tablets',
            'price': 549
            } 
}

my_app/__init__.py
from flask import Flask
from my_app.product.views import product_blueprint
from redis import Redis

app = Flask(__name__)
app.register_blueprint(product_blueprint)
redis = Redis()

my_app/product/__init__.py
# No content.
# We need this file just to make this folder a python module.

my_app/product/views.py
import ccy
from werkzeug import abort
from flask import Blueprint
from flask import render_template, request
from my_app.product.models import PRODUCTS

product_blueprint = Blueprint('product', __name__)

@product_blueprint.route('/')
@product_blueprint.route('/home')
def home():
    return render_template('home.html', products=PRODUCTS)

@product_blueprint.route('/product/<key>')
def product(key):
    product = PRODUCTS.get(key)
    if not product:
        abort(404)
    return render_template('product.html', product=product)

@product_blueprint.app_template_filter('full_name')
def full_name_filter(product):
    return '{0} / {1}'.format(product['category'], product['name'])

@product_blueprint.app_template_filter('format_currency')
def format_currency_filter(amount):
    currency_code = ccy.countryccy(request.accept_languages.best[-2:])
    return '{0} {1}'.format(currency_code, amount)
'''
@product_blueprint.context_processor
def some_processor():
    def full_name(product):
    return {'full_name': full_name}
'''

my_app/templates/_helpers.html
{% macro render_field(name, class='', value='', type='') -%}
  <input type="{{ type }}" name="{{ name }}" value="{{ value }} class=
  {{ class }}">
{%- endmacro %}

my_app/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Flask Framework Cookbook</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css' )}}" media="screen" title="no title" charset="utf-8">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" media="screen" title="no title" charset="utf-8">
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a href="{{ url_for('product.home' )}}" class="navbar-brand">Flask Cookbook</a>
        </div>
      </div>
    </div>
    <div class="container">
      {% block container %}
      {% endblock %}
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js">
    </script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}">
    </script>
  </body>
</html>

my_app/templates/home.html
{% extends 'base.html' %}
{% from '_helpers.html' import render_field %}
{% block container %}
<fieldset>
  {{ render_field('username', 'icon-user') }}
  {{ render_field('password', 'icon-key', type='password') }}
</fieldset>
<div class="top-pad">
  {% for id, product in products.iteritems() %}
    <div class="well">
      <h2>
        <a href="{{ url_for('product.product', key=id) }}">{{ product['name'] }}</a>
        <small>$ {{ product['price'] }}</small>
      </h2>
    </div>
  {% endfor %}
</div>
{% endblock %}

my_app/templates/index.html
<html>
    <head>
        <title>Flask Framework Cookbook</title>
    </head>
    <body>
        <h1>Hello {{ user }}</h1>
        <p>Welcome to the world of Flask!</p>
    </body>
</html>

my_app/templates/product.html
{% extends 'home.html'%}

{% block container %}
  <div class="top-pad">
      <h4>{{ product|full_name }}</h4>
    <h1>
      {{ product['name'] }}
      <small>{{ product['category'] }}</small>
    </h1>
    <h3>{{ product['price']|format_currency }}</h3>

  </div>
{% endblock %}